version: 2
jobs:
  publish:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -f Dockerfile -t ${USERNAME}/${IMAGE}:${TAG} .
      - run:
          name: Authenticate with Docker Hub
          command: docker login --username ${USERNAME} --password ${PASSWORD}
      - run:
          name: Push Docker Image
          command: docker push ${USERNAME}/${IMAGE}
workflows:
  version: 2
  update_image:
    jobs:
      - publish:
          filters:
            branches:
              only: master
